USE [master]
GO

/****** Object:  Database [CHTL]    Script Date: 4/22/2025 8:09:32 PM ******/
CREATE DATABASE [CHTL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CHTL', FILENAME = N'F:\sql2012\MSSQL11.SQLEXPRESS\MSSQL\DATA\CHTL.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CHTL_log', FILENAME = N'F:\sql2012\MSSQL11.SQLEXPRESS\MSSQL\DATA\CHTL_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CHTL] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CHTL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CHTL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CHTL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CHTL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CHTL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CHTL] SET ARITHABORT OFF 
GO

ALTER DATABASE [CHTL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CHTL] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CHTL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CHTL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CHTL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CHTL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CHTL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CHTL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CHTL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CHTL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CHTL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CHTL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CHTL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CHTL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CHTL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CHTL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CHTL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CHTL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CHTL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CHTL] SET  MULTI_USER 
GO

ALTER DATABASE [CHTL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CHTL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CHTL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CHTL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CHTL] SET  READ_WRITE 
GO


